import type { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'p-rmad-home',
    slug: 'real-madrid-home-24-25',
    name: 'Real Madrid Home 24/25',
    team: 'Real Madrid',
    league: 'La Liga',
    collection: 'European Clubs',
    type: 'player',
    price: 38000,
    currency: 'NGN',
    colors: [{ name: 'Pure White', hex: '#f4f4f4' }],
    images: {
      front: '/jerseys/real-madrid-home.jpg',
      back: '/jerseys/real-madrid-home.jpg',
      detail: '/jerseys/real-madrid-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['champions-league', 'la-liga', 'name-set'] },
    bestseller: true,
    inStock: true,
    description:
      'The iconic all-white home shirt, reimagined for the 24/25 season. Lightweight, breathable and built for matchday or the streets.',
    details: [
      { label: 'Fit', value: 'Regular athletic fit' },
      { label: 'Material', value: '100% recycled polyester, moisture-wicking' },
      { label: 'Printing', value: 'Heat-pressed official detailing' },
      { label: 'Care', value: 'Machine wash cold, inside out' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
  {
    id: 'p-bar-home',
    slug: 'barcelona-home-24-25',
    name: 'Barcelona Home 24/25',
    team: 'FC Barcelona',
    league: 'La Liga',
    collection: 'European Clubs',
    type: 'player',
    price: 38000,
    currency: 'NGN',
    colors: [{ name: 'Blaugrana', hex: '#a50044' }],
    images: {
      front: '/jerseys/barcelona-home.jpg',
      back: '/jerseys/barcelona-home.jpg',
      detail: '/jerseys/barcelona-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['champions-league', 'la-liga', 'name-set'] },
    bestseller: true,
    inStock: true,
    description:
      'The unmistakable Blaugrana stripes. A modern take on a timeless home kit with a clean, confident finish.',
    details: [
      { label: 'Fit', value: 'Slim athletic fit' },
      { label: 'Material', value: 'AEROREADY recycled knit' },
      { label: 'Printing', value: 'Sublimated stripes' },
      { label: 'Care', value: 'Machine wash cold' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
  {
    id: 'p-mci-home',
    slug: 'manchester-city-home-24-25',
    name: 'Manchester City Home 24/25',
    team: 'Manchester City',
    league: 'Premier League',
    collection: 'European Clubs',
    type: 'player',
    price: 36000,
    currency: 'NGN',
    colors: [{ name: 'Sky Blue', hex: '#6cabdd' }],
    images: {
      front: '/jerseys/mancity-home.jpg',
      back: '/jerseys/mancity-home.jpg',
      detail: '/jerseys/mancity-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['premier-league', 'champions-league', 'name-set'] },
    inStock: true,
    description:
      'Sharp sky-blue home shirt with tonal detailing. Engineered for performance and everyday wear.',
    details: [
      { label: 'Fit', value: 'Regular fit' },
      { label: 'Material', value: 'Primegreen recycled fabric' },
      { label: 'Printing', value: 'Heat-transfer crest' },
      { label: 'Care', value: 'Wash inside out, low heat' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
  {
    id: 'p-nga-home',
    slug: 'nigeria-super-eagles-home',
    name: 'Nigeria Super Eagles Home',
    team: 'Super Eagles',
    league: 'National',
    collection: 'National Teams',
    type: 'player',
    price: 35000,
    currency: 'NGN',
    colors: [{ name: 'Eagle Green', hex: '#0a8a3c' }],
    images: {
      front: '/jerseys/nigeria-home.jpg',
      back: '/jerseys/nigeria-home.jpg',
      detail: '/jerseys/nigeria-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['afcon', 'world-cup', 'name-set'] },
    bestseller: true,
    inStock: true,
    description:
      'Rep your nation in the Super Eagles home shirt. Green, bold and proudly Nigerian.',
    details: [
      { label: 'Fit', value: 'Regular fit' },
      { label: 'Material', value: 'Lightweight moisture-control knit' },
      { label: 'Printing', value: 'Embroidered crest' },
      { label: 'Care', value: 'Machine wash cold' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
  {
    id: 'p-psg-home',
    slug: 'paris-saint-germain-home-24-25',
    name: 'Paris Saint-Germain Home 24/25',
    team: 'Paris Saint-Germain',
    league: 'Ligue 1',
    collection: 'European Clubs',
    type: 'player',
    price: 39000,
    currency: 'NGN',
    colors: [{ name: 'Navy', hex: '#0a1f44' }],
    images: {
      front: '/jerseys/psg-home.jpg',
      back: '/jerseys/psg-home.jpg',
      detail: '/jerseys/psg-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['champions-league', 'name-set'] },
    isNew: true,
    inStock: true,
    description:
      'Deep navy home kit with signature red-and-white trim. Minimal, premium and unmistakably PSG.',
    details: [
      { label: 'Fit', value: 'Slim fit' },
      { label: 'Material', value: 'AEROREADY recycled knit' },
      { label: 'Printing', value: 'Heat-pressed detailing' },
      { label: 'Care', value: 'Wash cold, hang dry' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
  {
    id: 'p-ars-home',
    slug: 'arsenal-home-24-25',
    name: 'Arsenal Home 24/25',
    team: 'Arsenal',
    league: 'Premier League',
    collection: 'European Clubs',
    type: 'player',
    price: 37000,
    currency: 'NGN',
    colors: [{ name: 'Gunners Red', hex: '#ef0107' }],
    images: {
      front: '/jerseys/arsenal-home.jpg',
      back: '/jerseys/arsenal-home.jpg',
      detail: '/jerseys/arsenal-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['premier-league', 'name-set'] },
    inStock: true,
    description:
      'The famous red home shirt with white sleeves. A clean, classic Arsenal silhouette.',
    details: [
      { label: 'Fit', value: 'Regular fit' },
      { label: 'Material', value: 'Primegreen recycled fabric' },
      { label: 'Printing', value: 'Heat-transfer crest' },
      { label: 'Care', value: 'Wash inside out' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
  {
    id: 'p-liv-home',
    slug: 'liverpool-home-24-25',
    name: 'Liverpool Home 24/25',
    team: 'Liverpool',
    league: 'Premier League',
    collection: 'European Clubs',
    type: 'player',
    price: 37000,
    currency: 'NGN',
    colors: [{ name: 'Liverpool Red', hex: '#c8102e' }],
    images: {
      front: '/jerseys/liverpool-home.jpg',
      back: '/jerseys/liverpool-home.jpg',
      detail: '/jerseys/liverpool-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['premier-league', 'name-set'] },
    inStock: true,
    description:
      'The bold red home shirt with white trim. Made to be worn with pride on the Kop or at home.',
    details: [
      { label: 'Fit', value: 'Regular fit' },
      { label: 'Material', value: 'Moisture-wicking recycled knit' },
      { label: 'Printing', value: 'Sublimated detailing' },
      { label: 'Care', value: 'Machine wash cold' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
  {
    id: 'p-mia-home',
    slug: 'inter-miami-home-24-25',
    name: 'Inter Miami Home 24/25',
    team: 'Inter Miami',
    league: 'MLS',
    collection: 'MLS',
    type: 'player',
    price: 42000,
    currency: 'NGN',
    colors: [{ name: 'Miami Pink', hex: '#f0e0d6' }],
    images: {
      front: '/jerseys/intermiami-home.jpg',
      back: '/jerseys/intermiami-home.jpg',
      detail: '/jerseys/intermiami-home.jpg',
    },
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeveTypes: ['short', 'long'],
    customizable: true,
    customization: { name: true, number: true, patches: ['name-set', 'world-cup'] },
    isNew: true,
    inStock: true,
    description:
      'The standout pink home kit that took the world by storm. A statement piece for any collection.',
    details: [
      { label: 'Fit', value: 'Slim athletic fit' },
      { label: 'Material', value: 'AEROREADY recycled knit' },
      { label: 'Printing', value: 'Heat-pressed detailing' },
      { label: 'Care', value: 'Wash cold' },
    ],
    delivery: 'Dispatched within 24 hours. Delivered 3–5 business days nationwide.',
  },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

// Derived collections for the homepage / shop.
export const COLLECTIONS = [
  { id: 'european-clubs', name: 'European Clubs', description: 'The biggest clubs in world football.', image: '/jerseys/real-madrid-home.jpg', match: (p: Product) => p.collection === 'European Clubs' },
  { id: 'national-teams', name: 'National Teams', description: 'Rep your country, home or away.', image: '/jerseys/nigeria-home.jpg', match: (p: Product) => p.collection === 'National Teams' },
  { id: 'mls', name: 'MLS', description: 'Bold kits from across the Atlantic.', image: '/jerseys/intermiami-home.jpg', match: (p: Product) => p.collection === 'MLS' },
];

export const LEAGUES = Array.from(new Set(PRODUCTS.map((p) => p.league)));
export const TYPES: Product['type'][] = ['player', 'fan', 'retro'];
